name: master

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 5 * * 6'
    

jobs:
  publish_docker_image:
    name: Publish Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          APP_VERSION=$(date '+%Y-%m-%d')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker images
        id: docker_build_image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            cnbian/jellyfin:${{ env.APP_VERSION }}
            cnbian/jellyfin:latest
            ghcr.io/jerrybian/jellyfin:latest
            ghcr.io/jerrybian/jellyfin:${{ env.APP_VERSION }}

      - run: |
          date=$(date -d '+8 hour' '+%Y-%m-%d %H:%M:%S')
          git config --global user.email "JerryBian@outlook.com"
          git config --global user.name "GitHub Action Schedule"
          echo "$date" > _timestamp.txt
          git add .
          git commit -m ":100: $date"
          git push